# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler_coordination.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63rawler_coordination.proto\x12\x0fstd_web_crawler\"\x19\n\x17RegisterAsWorkerRequest\"#\n\x15RegisterAsWorkerReply\x12\n\n\x02id\x18\x01 \x01(\t\"~\n\x0eGetJobsRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0blast_job_id\x18\x02 \x01(\t\x12\x33\n\x0flast_job_status\x18\x03 \x01(\x0e\x32\x1a.std_web_crawler.JobStatus\x12\x16\n\x0elast_job_error\x18\x04 \x01(\t\"8\n\x0cGetJobsReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07retries\x18\x03 \x01(\t*%\n\tJobStatus\x12\x0c\n\x08\x46INISHED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\xc4\x01\n\tScheduler\x12\x66\n\x10RegisterAsWorker\x12(.std_web_crawler.RegisterAsWorkerRequest\x1a&.std_web_crawler.RegisterAsWorkerReply\"\x00\x12O\n\x07GetJobs\x12\x1f.std_web_crawler.GetJobsRequest\x1a\x1d.std_web_crawler.GetJobsReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawler_coordination_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOBSTATUS']._serialized_start=297
  _globals['_JOBSTATUS']._serialized_end=334
  _globals['_REGISTERASWORKERREQUEST']._serialized_start=47
  _globals['_REGISTERASWORKERREQUEST']._serialized_end=72
  _globals['_REGISTERASWORKERREPLY']._serialized_start=74
  _globals['_REGISTERASWORKERREPLY']._serialized_end=109
  _globals['_GETJOBSREQUEST']._serialized_start=111
  _globals['_GETJOBSREQUEST']._serialized_end=237
  _globals['_GETJOBSREPLY']._serialized_start=239
  _globals['_GETJOBSREPLY']._serialized_end=295
  _globals['_SCHEDULER']._serialized_start=337
  _globals['_SCHEDULER']._serialized_end=533
# @@protoc_insertion_point(module_scope)
